### ISSUE TITLE
Can't Download Image from Canvas in iOS browsers

### ISSUE THREAD

**Issue by taotheadmeow** [exzenous/cosnatsu-imgcampaign#8]
Download get stuck at 0%

**Comment by exzenous** [comment]
Sorry I couldn't reproduce that on my side
![IMG_8289](https://user-images.githubusercontent.com/33378035/199085642-c4bbb6b3-762d-4630-beb5-45fd989df48a.PNG)

**Comment by taotheadmeow** [comment]
I just found that is a WebKit on iOS problem. Not your code, but I'll find the way to work around to solve this problem.

**Comment by taotheadmeow** [comment]
I found solution to fix this! Check out this [commit](https://github.com/taotheadmeow/cosnatsu-imgcampaign-mod/commit/fc65f89d62681189c2c9ecd4c094e3557b643583).
